
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let DATA=null, exIndex=0, round=1, mode='single', phase='left', remaining=0, timer=null, pauseTimer=null, soundOn=true, ctx=null;
function show(id){$$('.screen').forEach(s=>s.classList.remove('active'));$('#'+id).classList.add('active');scrollTo(0,0)}
function beep(freq=650,d=.07,vol=.06){if(!soundOn)return;try{const A=window.AudioContext||window.webkitAudioContext;if(!ctx)ctx=new A();if(ctx.state==='suspended')ctx.resume();const o=ctx.createOscillator(),g=ctx.createGain();o.type='sine';o.frequency.value=freq;g.gain.setValueAtTime(vol,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+d);o.connect(g);g.connect(ctx.destination);o.start();o.stop(ctx.currentTime+d)}catch(e){}}
function fmt(s){return `00:${String(Math.max(0,s)).padStart(2,'0')}`}
function renderGrid(){const g=$('#exerciseGrid');g.innerHTML='';DATA.exercises.forEach((e,i)=>{const b=document.createElement('button');b.className='exercise-card';const im=e.images[0];b.innerHTML=`<div class="thumb"><img src="./${im}" alt=""><span class="brand-cover"></span></div><div class="card-copy"><h3>${e.title}</h3><p>${e.teaser}</p></div>`;b.onclick=()=>openDetail(i);g.appendChild(b)})}
function openDetail(i){exIndex=i;const e=DATA.exercises[i];$('#detailTitle').textContent=e.title;$('#detailTeaser').textContent=e.teaser;$('#detailSteps').innerHTML=e.soGehts.map(x=>`<li>${x}</li>`).join('');$('#detailFocus').textContent=e.focus;$('#detailBenefit').textContent=e.benefit;const v=$('#detailVisual');v.innerHTML='';e.images.forEach((im,n)=>{const f=document.createElement('figure');f.className='pose';f.innerHTML=`<img src="./${im}" class="${e.mirror&&e.mirror[n]?'mirror':''}" alt="${e.labels[n]}"><span class="brand-cover"></span><figcaption>${e.labels[n]}</figcaption>`;v.appendChild(f)});show('detail')}
function startExercise(single=true){mode=single?'single':'training';phase='left';remaining=DATA.training.workSeconds;renderTimer();show('timer');beep(760,.1,.07);clearInterval(timer);timer=setInterval(tick,1000)}
function renderTimer(){const e=DATA.exercises[exIndex];$('#timerTitle').textContent=e.title.toUpperCase();$('#roundChip').textContent=mode==='training'?`RUNDE ${round} VON ${DATA.training.rounds}`:'EINZELÜBUNG';$('#sideLabel').textContent=phase==='left'?'LINKES BEIN':'RECHTES BEIN';$('#clock').textContent=fmt(remaining);$('#timerCue').textContent=e.timerCue;const imgIndex=phase==='left'?0:Math.min(1,e.images.length-1);$('#timerImage').src='./'+e.images[imgIndex];$('#timerImage').classList.toggle('mirror',!!(e.mirror&&e.mirror[imgIndex]));$('#ringBar').style.width=(remaining/DATA.training.workSeconds*100)+'%'}
function tick(){remaining--;renderTimer();if(remaining<=3&&remaining>0)beep(470+remaining*70,.05,.04);if(remaining<=0){clearInterval(timer);if(phase==='left'){startSwitch()}else{finishExercise()}}}
function startSwitch(){show('switch');let n=DATA.training.switchSeconds;$('#switchCount').textContent=n;beep(820,.12,.07);const sw=setInterval(()=>{n--;$('#switchCount').textContent=Math.max(0,n);if(n>0)beep(520+n*60,.05,.04);if(n<=0){clearInterval(sw);phase='right';remaining=DATA.training.workSeconds;renderTimer();show('timer');beep(760,.08,.06);timer=setInterval(tick,1000)}},1000)}
function finishExercise(){beep(880,.12,.07);if(mode==='single'){show('overview');return}let isLast=exIndex===DATA.exercises.length-1;if(isLast&&round>=DATA.training.rounds){show('finish');return}let nextIndex=exIndex+1;if(isLast){round++;nextIndex=0}const n=DATA.exercises[nextIndex];$('#nextTitle').textContent=n.title;$('#nextTeaser').textContent=n.teaser;show('pause');let p=DATA.training.pauseSeconds;$('#pauseCount').textContent=p;clearInterval(pauseTimer);pauseTimer=setInterval(()=>{p--;$('#pauseCount').textContent=Math.max(0,p);if(p<=3&&p>0)beep(440+p*70,.04,.04);if(p<=0){clearInterval(pauseTimer);exIndex=nextIndex;phase='left';remaining=DATA.training.workSeconds;renderTimer();show('timer');timer=setInterval(tick,1000)}},1000);$('#skipPause').onclick=()=>{clearInterval(pauseTimer);exIndex=nextIndex;phase='left';remaining=DATA.training.workSeconds;renderTimer();show('timer');timer=setInterval(tick,1000)}}
function startTraining(){exIndex=0;round=1;mode='training';phase='left';remaining=DATA.training.workSeconds;renderTimer();show('timer');beep(760,.1,.07);timer=setInterval(tick,1000)}
function reset(){clearInterval(timer);clearInterval(pauseTimer);round=1;exIndex=0;show('overview')}
$('#startTraining').onclick=startTraining;$('#startExercise').onclick=()=>startExercise(true);$('#again').onclick=startTraining;$('#homeBtn').onclick=reset;$('#quitTimer').onclick=reset;$$('[data-back]').forEach(b=>b.onclick=()=>show('overview'));$$('.sound').forEach(b=>b.onclick=()=>{soundOn=!soundOn;$$('.sound').forEach(x=>x.textContent=soundOn?'♪':'×');if(soundOn)beep(700,.05,.04)});
fetch('./training.json').then(r=>r.json()).then(d=>{DATA=d;renderGrid();const q=new URLSearchParams(location.search);if(q.get('detail'))openDetail(Number(q.get('detail'))||0)}).catch(e=>{document.body.innerHTML='<main style="padding:30px"><h1>Training konnte nicht geladen werden.</h1></main>'});
if('serviceWorker' in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{});
